<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.1.2" />
    <PackageReference Include="AngleSharp.Css" Version="1.0.0-beta.144" />
    <PackageReference Include="AngleSharp.XPath" Version="2.0.4" />
    <PackageReference Include="Selenium.WebDriver" Version="4.25.0" />
  </ItemGroup>

</Project>
